#!/bin/bash
source ${SHYFT_BASE}/scripts/functions.sh
set -eu
if [[ "${HIGGS_NOSCALE:-0}" -ne 0 ]]; then
    EXTRA_HIGGS='noscale'
else
    EXTRA_HIGGS=''
fi
mkdir -p higgs${EXTRA_HIGGS}
INTEGRALS=$(printIntegrals.py -rv higgs${EXTRA_HIGGS}/nominal_all.root)

for NAME in data_obs Stop450 Top WJets ZJets SingleTop DiBoson QCD; do
    eval $(echo $NAME=$(echo "$INTEGRALS" | grep "^${NAME}:" | awk '{print $2}'))
done

# Fix all systematics to central value to get syst unc
if is_stale fitout/log_statonly${EXTRA_HIGGS}.txt nominal.root central.mrf fitout/log_central.txt z_diboson_constr.mrf z_diboson_def.mrf qcd_sf.mrf sm_constr.mrf lftag_sf.mrf jes_sf.mrf btag_sf.mrf; then
    cp central.mrf central_statonly${EXTRA_HIGGS}.mrf
    AWKSTR='/^Fit Results:/{flag=1;next}/^$/{flag=0}flag {print "+ fixParamVal = " $2 "=" $4}'
    awk "$AWKSTR" fitout/log_central.txt | grep -e 'qcd_' -e 'btag' -e 'jes' -e 'lftag' >> central_statonly${EXTRA_HIGGS}.mrf

    multiRegionFitter.exe central_statonly${EXTRA_HIGGS}.mrf \
    templateFile=nominal.root \
    output=fitout/statonly${EXTRA_HIGGS} savePlots=1 saveTemplates=1 \
    includefiles=z_diboson_constr.mrf,z_diboson_def.mrf,qcd_sf.mrf \
    includefiles=sm_constr.mrf,btag_sf.mrf,lftag_sf.mrf,jes_sf.mrf \
    showcorrelations=1 fitData=1 | tee fitout/log_statonly${EXTRA_HIGGS}.txt
fi
get_uncertainties fitout/log_statonly${EXTRA_HIGGS}.txt
get_scale_factors fitout/log_statonly${EXTRA_HIGGS}.txt

if [[ -z "$EXTRA_HIGGS" ]]; then
    echo "$Stop450_SF" > stop_sf.txt
else
    echo "$Stop450_SF" > stop_sf_${EXTRA_HIGGS}.txt
fi
if [[ "${HIGGS_NOSCALE:-0}" -ne 0 ]]; then
    set -x
    Stop450_UNC=$(perl -e "printf '%.4f',  abs( ($Stop450_UNC )/ ($Stop450_SF) )")
    Stop450_SF=1.0
    set +x
fi

for NAME in Stop450 Top WJets ZJets SingleTop DiBoson; do
    REALUNC="${NAME}_UNC"
    REALSF="${NAME}_SF"
    eval $(echo ${NAME}_ABSUNC=$(perl -e "printf '%.4f', 1.0 + abs(${!REALUNC} / ${!REALSF})"))
    eval $(echo ${NAME}_ABSUNC2=$(perl -e "printf '%.4f', 1.0 - abs(${!REALUNC} / ${!REALSF})"))
done


cat << EOF > higgs${EXTRA_HIGGS}_datacard.txt

# generated by make_datacard.sh

imax 1
jmax 6
kmax *

---------------------------------------------------------------------
shapes * * nominal_all.root \$PROCESS \$PROCESS_\$SYSTEMATIC
---------------------------------------------------------------------

bin      shyft
observation ${data_obs}
---------------------------------------------------------------------
bin        shyft shyft shyft shyft     shyft   shyft shyft
process        0     1     2     3         4       5     6
process  Stop450   Top WJets ZJets SingleTop DiBoson   QCD
rate    $Stop450  $Top $WJets $ZJets $SingleTop $DiBoson $QCD
---------------------------------------------------------------------

jec shape   1.00  1.00  1.00  1.00      1.00    1.00  1.00
jes shape   1.00  1.00  1.00  1.00      1.00    1.00  1.00
btag shape  1.00  1.00  1.00  1.00      1.00    1.00  1.00
lftag shape 1.00  1.00  1.00  1.00      1.00    1.00  1.00
lumi lnN    1.026 1.026  1.026  1.026      1.026    1.026  1.026
$( :
# Add in systematics that only exist in the new world
#if [[ "$(basename $(dirname $(pwd)))" == "OLD" ]]; then
#    :
#else
#    echo 'ttmatching shape2 - 1.00    -     -         -       -  -
#ttscale shape2 -   1.00     -     -         -       -  -
#wmatching shape2 -    -  1.00     -         -       -  -
#wscale shape2 -       -  1.00     -         -       -  -'
#fi
)
$(

# Extract systematics
#echo "stat0 lnN $Stop450_ABSUNC $Top_ABSUNC $WJets_ABSUNC $ZJets_ABSUNC $SingleTop_ABSUNC - -"
#echo "stat1 lnN - - $WJets_ABSUNC $ZJets_ABSUNC - - -"
# All uncorrelated
#echo "stat0 lnN $Stop450_ABSUNC - - - - - -"
#echo "stat1 lnN - $Top_ABSUNC - - - - -"
#echo "stat2 lnN - - $WJets_ABSUNC - - - - "
#echo "stat3 lnN - - - $ZJets_ABSUNC - - -"
#echo "stat4 lnN - - - - $SingleTop_ABSUNC - -"
#echo "stat5 lnN - - - - - $DiBoson_ABSUNC -"
#echo "qcd_unc lnN - - - - - - - 2.0"
# All correlated
#echo "stat0 lnN $Stop450_ABSUNC $Top_ABSUNC $WJets_ABSUNC $ZJets_ABSUNC $SingleTop_ABSUNC $DiBoson_ABSUNC 2.0"

# cardtest 0
#echo "stat0 lnN $Stop450_ABSUNC $Top_ABSUNC2 - - - - -"
#echo "stat1 lnN - $Top_ABSUNC - - - - -"
#echo "stat2 lnN - - $WJets_ABSUNC $ZJets_ABSUNC2 - - - "
#echo "stat4 lnN - - - - $SingleTop_ABSUNC - -"
#echo "stat5 lnN - - - - - $DiBoson_ABSUNC -"
#echo "stat6 lnN - - - - - - - 2.0"

# Some correlated
#echo "stat0 lnN $Stop450_ABSUNC $Top_ABSUNC2 - - - - -"
#echo "stat1 lnN - - - - $SingleTop_ABSUNC - -"
#echo "stat2 lnN - - $WJets_ABSUNC $ZJets_ABSUNC2 - - - "
#echo "stat5 lnN - - - - - $DiBoson_ABSUNC -"
#echo "stat6 lnN - - - - - - - 2.0"

# Decompose covariance matrix
AWKSTR='/^Decomposed Covariance Matrix:/{flag=1;next}/^$/{flag=0}flag {print}' 
awk "$AWKSTR" fitout/log_statonly.txt | ./extract_covar.py

#echo "qcd_unc lnN - - - - - - - 2.0"

)
EOF
cat higgs${EXTRA_HIGGS}_datacard.txt
